### ISSUE TITLE
access to has_one/has_many objects

### ISSUE THREAD

**Issue by Fivell** [chingor13/json_api_client#60]
Hello, I'm interested in using json-api , so investigating this stuff.
There is demo application https://github.com/cerebris/peeps based on ```gem 'jsonapi-resources'```

using ```json_api_client``` I'm able to load contact with all phone-numbers, using  ```include```

Here is my code 
```ruby
module MyApi

  class Base < JsonApiClient::Resource
    self.site = "http://127.0.0.1:3000/"
  end

  class PhoneNumber < Base
    belongs_to :contact
  end
  
  class Contact < Base
    has_many :phone_numbers, class_name: "PhoneNumber"
  end

end
payload = MyApi::Contact.find(id: 1, include: 'phone_numbers')
```
URI: http://127.0.0.1:3000/contacts/1?include=phone-numbers
Response status   Net::HTTPOK (200)

  Response body  
```
{
    "data": {
        "id": "1",
        "name_first": "John",
        "name_last": "Doe",
        "email": "john.doe@boring.test",
        "twitter": null,
        "type": "contacts",
        "links": {
            "self": "http://127.0.0.1:3000/contacts/1",
            "phone_numbers": {
                "self": "http://127.0.0.1:3000/contacts/1/links/phone-numbers",
                "related": "http://127.0.0.1:3000/contacts/1/phone-numbers",
                "linkage": [{
                    "type": "phone-numbers",
                    "id": "1"
                }]
            }
        }
    },
    "included": [{
        "id": "1",
        "name": "home",
        "phone_number": "(603) 555-1212",
        "type": "phone_numbers",
        "links": {
            "self": "http://127.0.0.1:3000/phone-numbers/1",
            "contact": {
                "self": "http://127.0.0.1:3000/phone-numbers/1/links/contact",
                "related": "http://127.0.0.1:3000/phone-numbers/1/contact",
                "linkage": {
                    "type": "contacts",
                    "id": "1"
                }
            }
        }
    }]
}
```

And now  I wan't access included phone numbers
and get Error
```
payload.first.phone_numbers
NoMethodError: undefined method `[]' for nil:NilClass
	from /Users/igor/.rvm/gems/ruby-2.1.5@jso_api/bundler/gems/json_api_client-a4465fd1e445/lib/json_api_client/linking/included_data.rb:44:in `record_for'
```

Should it work ?

**Comment by chingor13** [comment]
The has_one/belongs_to association declarations were a relic from my first version (pre 1.0 release candidates). They were used to generate nested routes. With the new link spec, you shouldn't have to declare the associations - in fact it is probably messing up where it's looking for the included records if it's being declared.

There should be tests for the included data specification, so let me know if removing the association declaration doesn't fix it.

**Comment by Fivell** [comment]
@chingor13 , thanks for response, now I'm trying next configuration 

```ruby
module MyApi
  class Base < JsonApiClient::Resource
    self.site = "http://127.0.0.1:3000/"
  end
  class PhoneNumber < Base
  end
  class Contact < Base
  end
end

payload = MyApi::Contact.find(id: 1, include: 'phone_numbers')

```

```
[#<MyApi::Contact:0x007fc6fb062bc8
  @attributes=
   {"id"=>"1",
    "links"=>
     {"self"=>"http://127.0.0.1:3000/contacts/1",
      "phone_numbers"=>
       {"self"=>"http://127.0.0.1:3000/contacts/1/links/phone-numbers",
        "related"=>"http://127.0.0.1:3000/contacts/1/phone-numbers",
        "linkage"=>[{"type"=>"phone-numbers", "id"=>"1"}]}},
    "type"=>"contacts"},
  @linked_data=
   #<JsonApiClient::Linking::IncludedData:0x007fc6fb05b9b8
    @data=
     {"phone_numbers"=>
       {"1"=>
         #<MyApi::PhoneNumber:0x007fc6f96c6660
          @attributes=
           {"id"=>"1",
            "links"=>
             {"self"=>"http://127.0.0.1:3000/phone-numbers/1",
              "contact"=>
               {"self"=>"http://127.0.0.1:3000/phone-numbers/1/links/contact",
                "related"=>"http://127.0.0.1:3000/phone-numbers/1/contact",
                "linkage"=>{"type"=>"contacts", "id"=>"1"}}},
            "type"=>"phone_numbers"},
          @links=
           #<JsonApiClient::Linking::Links:0x007fc6f96c5a80
            @attributes=
             {"self"=>"http://127.0.0.1:3000/phone-numbers/1",
              "contact"=>
               {"self"=>"http://127.0.0.1:3000/phone-numbers/1/links/contact",
                "related"=>"http://127.0.0.1:3000/phone-numbers/1/contact",
                "linkage"=>{"type"=>"contacts", "id"=>"1"}}}>>}}>,
  @links=
   #<JsonApiClient::Linking::Links:0x007fc6fb061ef8
    @attributes=
     {"self"=>"http://127.0.0.1:3000/contacts/1",
      "phone_numbers"=>
       {"self"=>"http://127.0.0.1:3000/contacts/1/links/phone-numbers",
        "related"=>"http://127.0.0.1:3000/contacts/1/phone-numbers",
        "linkage"=>[{"type"=>"phone-numbers", "id"=>"1"}]}}>,
  @persisted=true>]
```

```ruby
 payload.first.phone_numbers
```

gives again
```
NoMethodError: undefined method `[]' for nil:NilClass
	from /Users/igor/.rvm/gems/ruby-2.1.5@console/bundler/gems/json_api_client-a4465fd1e445/lib/json_api_client/linking/included_data.rb:44:in `record_for'

```

**Comment by Fivell** [comment]
UPD, after updating jsonapi-resource , response looks like 
```json

 {
     "data": {
         "id": "1",
         "type": "contacts",
         "links": {
             "self": "http://127.0.0.1:3000/contacts/1"
         },
         "attributes": {
             "name_first": "John",
             "name_last": "Doe",
             "email": "john.doe@boring.test",
             "twitter": null
         },
         "relationships": {
             "phone_numbers": {
                 "links": {
                     "self": "http://127.0.0.1:3000/contacts/1/relationships/phone-numbers",
                     "related": "http://127.0.0.1:3000/contacts/1/phone-numbers"
                 },
                 "data": [{
                     "type": "phone_numbers",
                     "id": "1"
                 }]
             }
         }
     },
     "included": [{
         "id": "1",
         "type": "phone_numbers",
         "links": {
             "self": "http://127.0.0.1:3000/phone-numbers/1"
         },
         "attributes": {
             "name": "home",
             "phone_number": "(603) 555-1212"
         },
         "relationships": {
             "contact": {
                 "links": {
                     "self": "http://127.0.0.1:3000/phone-numbers/1/relationships/contact",
                     "related": "http://127.0.0.1:3000/phone-numbers/1/contact"
                 },
                 "data": {
                     "type": "contacts",
                     "id": "1"
                 }
             }
         }
     }]
 }
```

And I have another exception for ``` payload.first.phone_numbers```

```
NoMethodError: undefined method `phone_numbers' for #<MyApi::Contact:0x007fc6f340c470>
	from /Users/igor/.rvm/gems/ruby-2.1.5@console/bundler/gems/json_api_client-a4465fd1e445/lib/json_api_client/helpers/dynamic_attributes.rb:47:in `method_missing'

```
payload looks 

```
[#<MyApi::Contact:0x007fc6f340c470
  @attributes=
   {"id"=>"1",
    "links"=>{"self"=>"http://127.0.0.1:3000/contacts/1"},
    "type"=>"contacts",
    "name_first"=>"John",
    "name_last"=>"Doe",
    "email"=>"john.doe@boring.test",
    "twitter"=>nil},
  @linked_data=
   #<JsonApiClient::Linking::IncludedData:0x007fc6f9630408
    @data=
     {"phone_numbers"=>
       {"1"=>
         #<MyApi::PhoneNumber:0x007fc6f95e98f0
          @attributes=
           {"id"=>"1",
            "links"=>{"self"=>"http://127.0.0.1:3000/phone-numbers/1"},
            "type"=>"phone_numbers",
            "name"=>"home",
            "phone_number"=>"(603) 555-1212"},
          @links=
           #<JsonApiClient::Linking::Links:0x007fc6f95e8d10
            @attributes={"self"=>"http://127.0.0.1:3000/phone-numbers/1"}>>}}>,
  @links=
   #<JsonApiClient::Linking::Links:0x007fc6f6a54050
    @attributes={"self"=>"http://127.0.0.1:3000/contacts/1"}>,
  @persisted=true>]
```

**Comment by Fivell** [comment]
should be very easy way to access this
```ruby
payload.first.linked_data.data["phone_numbers"]["1"].data["attributes"]
```

```ruby
{"name"=>"home", "phone_number"=>"(603) 555-1212"}
```

cc @chingor13

**Comment by senid231** [comment]
I'm using json-api and interested in json_api_client.
what the status of this issue?

I think ```payload.first.linked_data.data["phone_numbers"]["1"]``` should be instance of MyApi::PhoneNumber.

And it should be accessed like this:
```ruby
contact = MyApi::Contact.find(id: 1, include: 'phone_numbers') # class MyApi::Contact
phone_number = contact.phone_numbers.first # class MyApi::PhoneNumber
phone_number.contact # class MyApi::Contact
```

**Comment by chingor13** [comment]
Which version are you guys using? The new links spec is in master which currently a 1.0 prerelease version which was tracking the RC3 of jsonapi.org. The prerelease version is on rubygems as 1.0.0.beta

**Comment by senid231** [comment]
i use master branch from github

**Comment by senid231** [comment]
[json-api:examples/index.md](https://github.com/json-api/json-api/blob/93e8c19c2584f1ccba20b69d6b97479ed4afdbfe/examples/index.md)
this file shows how responses should be look like by json api spec

I use json_api_client from github master with such configuration
```ruby
module Client
  class Base < JsonApiClient::Resource
    self.site = 'http://127.0.0.1:3000/'
  end

  class Contact < Base
    has_many :phone_numbers
  end

  class PhoneNumber < Base
    belongs_to :contact
  end
end
```
I use jsonapi_resource from github master with such configuration
```ruby
JSONAPI.configure do |config|
  config.json_key_format = :underscored_key
  config.route_format = :underscored_route
  config.top_level_meta_include_record_count = true
  config.top_level_links_include_pagination = true
  config.default_paginator = :paged
end

class ContactResource < JSONAPI::Resource
  attributes :name_first, :name_last, :email, :twitter
  has_many :phone_numbers
end

class PhoneNumberResource < JSONAPI::Resource
  attributes :name, :phone_number
  has_one :contact
  filter :contact
end
```
now Im trying to get index with includes
```ruby
payload = Client::Contact.includes(:phone_numbers).where(id: 1).first
```
and get this
```
#<Client::Contact:0x0000000460f6b8 @attributes={"id"=>"1", "links"=>{"self"=>"http://127.0.0.1:3000/contacts/1"}, "type"=>"contacts", "name_first"=>"John", "name_last"=>"Doe", "email"=>"john.doe@boring.test", "twitter"=>nil}, @links=#<JsonApiClient::Linking::Links:0x0000000460ea10 @attributes={"self"=>"http://127.0.0.1:3000/contacts/1"}>, @persisted=true, @linked_data=#<JsonApiClient::Linking::IncludedData:0x000000046075d0 @data={"phone_numbers"=>{"1"=>#<Client::PhoneNumber:0x000000045f5948 @attributes={"id"=>"1", "links"=>{"self"=>"http://127.0.0.1:3000/phone_numbers/1"}, "type"=>"phone_numbers", "name"=>"home", "phone_number"=>"(603) 555-1212"}, @links=#<JsonApiClient::Linking::Links:0x000000045f48b8 @attributes={"self"=>"http://127.0.0.1:3000/phone_numbers/1"}>>}}>>
```
server log:
```
Started GET "/contacts?filter%5Bid%5D=1&include=phone_numbers&page=1&per_page=1" for 127.0.0.1 at 2015-06-19 12:39:06 +0300
Processing by ContactsController#index as API_JSON
  Parameters: {"filter"=>{"id"=>"1"}, "include"=>"phone_numbers", "page"=>"1", "per_page"=>"1"}
  Contact Load (0.5ms)  SELECT  "contacts".* FROM "contacts" WHERE "contacts"."id" = 1  ORDER BY "contacts"."id" ASC LIMIT 10 OFFSET 0
  PhoneNumber Load (0.4ms)  SELECT "phone_numbers".* FROM "phone_numbers" WHERE "phone_numbers"."contact_id" IN (1)
   (2.1ms)  SELECT COUNT(*) FROM "contacts" WHERE "contacts"."id" = 1
"RESPONSE: ok\n"
{
        :data => [
        [0] {
                       "id" => "1",
                     "type" => "contacts",
                    "links" => {
                :self => "http://127.0.0.1:3000/contacts/1"
            },
               "attributes" => {
                "name_first" => "John",
                 "name_last" => "Doe",
                     "email" => "john.doe@boring.test",
                   "twitter" => nil
            },
            "relationships" => {
                "phone_numbers" => {
                    :links => {
                           :self => "http://127.0.0.1:3000/contacts/1/relationships/phone_numbers",
                        :related => "http://127.0.0.1:3000/contacts/1/phone_numbers"
                    },
                     :data => [
                        [0] {
                            :type => "phone_numbers",
                              :id => "1"
                        }
                    ]
                }
            }
        }
    ],
    :included => [
        [0] {
                       "id" => "1",
                     "type" => "phone_numbers",
                    "links" => {
                :self => "http://127.0.0.1:3000/phone_numbers/1"
            },
               "attributes" => {
                        "name" => "home",
                "phone_number" => "(603) 555-1212"
            },
            "relationships" => {
                "contact" => {
                    :links => {
                           :self => "http://127.0.0.1:3000/phone_numbers/1/relationships/contact",
                        :related => "http://127.0.0.1:3000/phone_numbers/1/contact"
                    },
                     :data => {
                        :type => "contacts",
                          :id => "1"
                    }
                }
            }
        }
    ],
        :meta => {
        "record_count" => 1
    },
       :links => {
        "first" => "http://127.0.0.1:3000/contacts?filter%5Bid%5D=1&include=phone_numbers&page%5Bnumber%5D=1&page%5Bsize%5D=10",
         "last" => "http://127.0.0.1:3000/contacts?filter%5Bid%5D=1&include=phone_numbers&page%5Bnumber%5D=1&page%5Bsize%5D=10"
    }
}
```
when we trying to get phone_numbers
```ruby
payload.phone_numbers
```
it raise an exception
```
NoMethodError: undefined method `phone_numbers' for #<Client::Contact:0x0000000460f6b8>
	from /home/senid/.rvm/gems/ruby-2.2.2@tmp/bundler/gems/json_api_client-a4465fd1e445/lib/json_api_client/helpers/dynamic_attributes.rb:47:in `method_missing'
	from /home/senid/.rvm/gems/ruby-2.2.2@tmp/bundler/gems/json_api_client-a4465fd1e445/lib/json_api_client/helpers/linkable.rb:37:in `method_missing'
	from (irb):15
	from /home/senid/.rvm/gems/ruby-2.2.2@tmp/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
	from /home/senid/.rvm/gems/ruby-2.2.2@tmp/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
	from /home/senid/.rvm/gems/ruby-2.2.2@tmp/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/senid/.rvm/gems/ruby-2.2.2@tmp/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/senid/.rvm/gems/ruby-2.2.2@tmp/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from /home/senid/projects/temp/peeps/bin/rails:8:in `require'
	from /home/senid/projects/temp/peeps/bin/rails:8:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'
```

when data should server send to make json_api_client map it to association?
it looks like server send correct data (according to jsonapi examples)

I create test project when you can test it [senid231/test_json_api](https://github.com/senid231/test_json_api)

**Comment by chingor13** [comment]
I merged the pull request that fixed reading relationships from the relationships section of the response. It's now in the 1_0 branch.

**Comment by Fivell** [comment]
fixed
