### ISSUE TITLE
nested resource losing parent key after update

### ISSUE THREAD

**Issue by senid231** [chingor13/json_api_client#78]
```ruby
class Base < JsonApiClient::Resource
  self.site = 'http://127.0.0.1:3000/'
end

class Author < Base
  has_many :posts
 end

class Post < Base
  belongs_to :author
end
```
```ruby
p = Client::Post.where(author_id: 1).find(1).first; 1
p.title = 'asd'
p.author_id # return 1
p.save # does not matter if it true or false
p.attributes
# {"id"=>"1", "links"=>{"self"=>"http://127.0.0.1:3000/posts/1"}, "type"=>"posts", "relationships"=>{"author"=>{"links"=>{"self"=>"http://127.0.0.1:3000/posts/1/relationships/author", "related"=>"http://127.0.0.1:3000/posts/1/author"}, "data"=>{"type"=>"authors", "id"=>"1"}}, "comments"=>{"links"=>{"self"=>"http://127.0.0.1:3000/posts/1/relationships/comments", "related"=>"http://127.0.0.1:3000/posts/1/comments"}}}, "title"=>"asd", "text"=>"text 1", "created_at"=>"2015-07-08T20:22:40.476Z"}
p.author_id
```
last row raise error
```
NoMethodError: undefined method `author_id' for #<Client::Post:0x000000055507f8>
	from /home/senid/.rvm/gems/ruby-2.2.2@peeps/bundler/gems/json_api_client-4b1a765d903a/lib/json_api_client/helpers/dynamic_attributes.rb:47:in `method_missing'
	from /home/senid/.rvm/gems/ruby-2.2.2@peeps/bundler/gems/json_api_client-4b1a765d903a/lib/json_api_client/helpers/relatable.rb:34:in `method_missing'
	from (irb):5
	from /home/senid/.rvm/gems/ruby-2.2.2@peeps/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
	from /home/senid/.rvm/gems/ruby-2.2.2@peeps/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
	from /home/senid/.rvm/gems/ruby-2.2.2@peeps/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/senid/.rvm/gems/ruby-2.2.2@peeps/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/senid/.rvm/gems/ruby-2.2.2@peeps/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from /home/senid/projects/temp/peeps/bin/rails:4:in `require'
	from /home/senid/projects/temp/peeps/bin/rails:4:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'
```

**Comment by Fivell** [comment]
according to this https://github.com/chingor13/json_api_client/blob/864e8f59ad4e90f8631fe18b9522779e32e00498/lib/json_api_client/helpers/requestable.rb#L38 it is expected behaviour,  response should contain author_id attribute
